///////////////////////////////////////////////////////////
//  Actividad_Perfil.cs
//  Implementation of the Class Actividad_Perfil
//  Generated by Enterprise Architect
//  Created on:      04-Oct-2011 11:03:52
//  Original author: Administrador
///////////////////////////////////////////////////////////




public class Actividad_Perfil {

	public Actividad_Perfil(){

	}

	~Actividad_Perfil(){

	}

	public virtual void Dispose(){

	}

	public void tienenPerfil(){

	}

}//end Actividad_Perfil