///////////////////////////////////////////////////////////
//  Actividad.cs
//  Implementation of the Class Actividad
//  Generated by Enterprise Architect
//  Created on:      04-Oct-2011 11:02:56
//  Original author: Leo
///////////////////////////////////////////////////////////




public class Actividad {

	private String nombre;
	private String tipo;
	public Secuencia m_Secuencia;
	public Actividad_Flash m_Actividad_Flash;
	public Perfil m_Perfil;

	public Actividad(){

	}

	~Actividad(){

	}

	public virtual void Dispose(){

	}

	public void mostrarActividad(){

	}

	/// 
	/// <param name="act"></param>
	public void mostrarActividadFlash(Actividad act){

	}

	public void obtenerActividad(){

	}

}//end Actividad