///////////////////////////////////////////////////////////
//  Alumno.cs
//  Implementation of the Class Alumno
//  Generated by Enterprise Architect
//  Created on:      04-Oct-2011 11:04:11
//  Original author: Leo
///////////////////////////////////////////////////////////




public class Alumno : Usuario {

	private int[] ActividadesParaRealizar;
	private int[] ActividadesRealizadas;
	private String nivelDiscapacidad;
	public Perfil m_Perfil;

	public Alumno(){

	}

	~Alumno(){

	}

	public override void Dispose(){

	}

	public int[] getActividadesParaRealizar(){

		return null;
	}

	public int[] getActividadesRealziadas(){

		return null;
	}

	public String getNivelDiscapacidad(){

		return "";
	}

	/// 
	/// <param name="act"></param>
	public void setActividadesParaRealizar(int[] act){

	}

	/// 
	/// <param name="act"></param>
	public void setActividadesRealizadas(int[] act){

	}

	/// 
	/// <param name="nivel"></param>
	public void setNivelDiscapacidad(String nivel){

	}

}//end Alumno