///////////////////////////////////////////////////////////
//  Avance.cs
//  Implementation of the Class Avance
//  Generated by Enterprise Architect
//  Created on:      04-Oct-2011 11:04:21
//  Original author: Leo
///////////////////////////////////////////////////////////




public class Avance {

	public Avance(){

	}

	~Avance(){

	}

	public virtual void Dispose(){

	}

	public void guardarAvance(){

	}

	public void obtenerAvance(){

	}

}//end Avance