///////////////////////////////////////////////////////////
//  Ayudante Técnico.cs
//  Implementation of the Class Ayudante Técnico
//  Generated by Enterprise Architect
//  Created on:      04-Oct-2011 11:04:16
//  Original author: Leo
///////////////////////////////////////////////////////////




public class Ayudante Técnico : Usuario {

	public Avance m_Avance;

	public Ayudante Técnico(){

	}

	~Ayudante Técnico(){

	}

	public override void Dispose(){

	}

	/// 
	/// <param name="nombre"></param>
	public void seleccionarActividad(String nombre){

	}

}//end Ayudante Técnico