///////////////////////////////////////////////////////////
//  GuiaVirtual.cs
//  Implementation of the Class GuiaVirtual
//  Generated by Enterprise Architect
//  Created on:      04-Oct-2011 11:04:30
//  Original author: Leo
///////////////////////////////////////////////////////////




public class GuiaVirtual {

	public GuiaVirtual(){

	}

	~GuiaVirtual(){

	}

	public virtual void Dispose(){

	}

	/// 
	/// <param name="param"></param>
	public void obtenerInstrucciones(String param){

	}

}//end GuiaVirtual