///////////////////////////////////////////////////////////
//  Perfil.cs
//  Implementation of the Class Perfil
//  Generated by Enterprise Architect
//  Created on:      04-Oct-2011 11:03:57
//  Original author: Leo
///////////////////////////////////////////////////////////




public class Perfil {

	private String Nombre;
	public Perfil_Actividad m_Perfil_Actividad;

	public Perfil(){

	}

	~Perfil(){

	}

	public virtual void Dispose(){

	}

	public String getNombre(){

		return "";
	}

	/// 
	/// <param name="nombre"></param>
	public void setNombre(String nombre){

	}

}//end Perfil