///////////////////////////////////////////////////////////
//  Profesor.cs
//  Implementation of the Class Profesor
//  Generated by Enterprise Architect
//  Created on:      04-Oct-2011 11:04:26
//  Original author: Leo
///////////////////////////////////////////////////////////




public class Profesor : Usuario {

	public Avance m_Avance;

	public Profesor(){

	}

	~Profesor(){

	}

	public override void Dispose(){

	}

	public void agregarUsuario(){

	}

	/// 
	/// <param name="param"></param>
	public void buscarPerfil(String param){

	}

	/// 
	/// <param name="nombre"></param>
	/// <param name="actividad"></param>
	public void crearPerfilAlumno(String nombre, String [] actividad){

	}

	public void inhabilitarUsuario(){

	}

	public void listarUsuarios(){

	}

	/// 
	/// <param name="nombre"></param>
	/// <param name="actividades"></param>
	public void modificarPerfilAlumno(String nombre, String[] actividades){

	}

	public void modificarUsuario(){

	}

	public void obtenerReporteActividadesRealizadas(){

	}

	/// 
	/// <param name="nombre"></param>
	public void seleccionarActividad(String nombre){

	}

}//end Profesor