///////////////////////////////////////////////////////////
//  Secuencia.cs
//  Implementation of the Class Secuencia
//  Generated by Enterprise Architect
//  Created on:      04-Oct-2011 11:03:46
//  Original author: Administrador
///////////////////////////////////////////////////////////




public class Secuencia {

	public Secuencia(){

	}

	~Secuencia(){

	}

	public virtual void Dispose(){

	}

	public void obtenerSecuencia(){

	}

}//end Secuencia