///////////////////////////////////////////////////////////
//  Usuario.cs
//  Implementation of the Class Usuario
//  Generated by Enterprise Architect
//  Created on:      04-Oct-2011 11:04:05
//  Original author: Leo
///////////////////////////////////////////////////////////




public class Usuario {

	private String apellido;
	private Date fechaNacimiento;
	private String nombre;
	private String nombreUsuario;
	private String password;
	public GuiaVirtual m_GuiaVirtual;

	public Usuario(){

	}

	~Usuario(){

	}

	public virtual void Dispose(){

	}

	/// 
	/// <param name="usuario"></param>
	/// <param name="password"></param>
	public void autentificarUsuario(String usuario, String password){

	}

	/// 
	/// <param name="String"></param>
	public void existeUsuario(nombreUsuario String){

	}

	public String apellido getApellido(){

		return null;
	}

	public Date getFechaNacimiento(){

		return null;
	}

	public String getNombre(){

		return "";
	}

	public String getNombreUsuario(){

		return "";
	}

	public String getPassword(){

		return "";
	}

	/// 
	/// <param name="apellido"></param>
	public void setApellido(String apellido){

	}

	/// 
	/// <param name="fecha"></param>
	public void setFechaNacimiento(Date fecha){

	}

	/// 
	/// <param name="nombre"></param>
	public void setNombre(String nombre){

	}

	/// 
	/// <param name="nombreUsuario"></param>
	public void setNombreUsuario(String nombreUsuario){

	}

	/// 
	/// <param name="password"></param>
	public void setPassword(String password){

	}

}//end Usuario